export type CheckIn={user_id:string;date:string;sleep_hours:number|null;sleep_quality:number|null;energy:number|null;mood:number|null;stress:number|null;soreness:number|null;note:string};
export type Habit={id:string;user_id:string;name:string;icon:string;frequency:'diário'|'dias da semana';weekdays:number[];target:number|null;archived:boolean;source:'manual'|'water'|'workout';created_at:string};
export type HabitLog={habit_id:string;user_id:string;date:string;done:boolean;value:number|null};
export function shiftDate(date:string,offset:number){return new Date(Date.parse(date+'T00:00:00Z')+offset*86400000).toISOString().slice(0,10);}
export function scheduledHabit(habit:Pick<Habit,'frequency'|'weekdays'>,date:string){return habit.frequency==='diário'||habit.weekdays.includes(new Date(date+'T00:00:00Z').getUTCDay());}
export function habitStats(habit:Habit,logs:HabitLog[],today:string){const owned=logs.filter(l=>l.habit_id===habit.id&&l.date<=today),done=new Set(owned.filter(l=>l.done).map(l=>l.date));const start=owned.map(l=>l.date).sort()[0]||today;const days=Math.min(36500,Math.max(0,Math.round((Date.parse(today)-Date.parse(start))/86400000)));let best=0,streak=0;for(let i=days;i>=0;i--){const day=shiftDate(today,-i);if(!scheduledHabit(habit,day))continue;streak=done.has(day)?streak+1:0;best=Math.max(best,streak);}let current=0;for(let i=0;i<=days+7;i++){const day=shiftDate(today,-i);if(!scheduledHabit(habit,day))continue;if(i===0&&!done.has(day))continue;if(!done.has(day))break;current++;}return {current,best,calendar:Array.from({length:90},(_,i)=>{const date=shiftDate(today,i-89);return {date,scheduled:scheduledHabit(habit,date),done:done.has(date)};})};}
export function derivedHabitLogs(habit:Habit,store:{waterEntries:{date:string;amount:number}[];sessions:string[];day:string;water:number;waterGoal:number}):HabitLog[]{if(habit.source==='manual')return [];const iso=(d:string)=>d.includes('/')?d.split('/').reverse().join('-'):d;const values:Record<string,number>={};if(habit.source==='water'){for(const e of store.waterEntries)values[iso(e.date)]=(values[iso(e.date)]||0)+e.amount;values[iso(store.day)]=store.water;}else for(const date of store.sessions)values[iso(date)]=1;return Object.entries(values).map(([date,value])=>({habit_id:habit.id,user_id:habit.user_id,date,value,done:value>=(habit.target||(habit.source==='water'?store.waterGoal:1))}));}
export function canShowCorrelations(rows:Pick<CheckIn,'date'>[]){return new Set(rows.map(r=>r.date)).size>=21;}
export function movingAverage(rows:CheckIn[],key:Exclude<keyof CheckIn,'user_id'|'date'|'note'>){return rows.filter(r=>r[key]!==null).map(r=>{const available=rows.filter(other=>other.date>=shiftDate(r.date,-6)&&other.date<=r.date&&other[key]!==null);return {date:r.date,value:available.reduce((sum,r)=>sum+(r[key]||0),0)/available.length};});}
