import {exercises} from '../../../src/data/exercises.ts';
import {detectPlateaus,weeklyMuscleBalance,exercisePerformance,isoDate,type AnalyticsLog} from '../../../src/lib/analytics/index.ts';
import {habitStats,type Habit,type HabitLog,type CheckIn} from '../../../src/lib/habits.ts';
export type CoachData={workouts:AnalyticsLog[];meals:{date:string;calories:number;protein:number;carbs:number;fat:number}[];weights:{date:string;value:number}[];checkins:CheckIn[];pain:{date:string;region:string;intensity:number}[];habits:Habit[];habitLogs:HabitLog[];plannedDays:number;wellbeingRisk:boolean};
const mean=(values:number[])=>values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length*10)/10:null;
export function coachContext(data:CoachData,today:string){const start=new Date(Date.parse(today+'T00:00:00Z')-6*86400000).toISOString().slice(0,10);const weekly=data.workouts.filter(r=>isoDate(r.date)>=start&&isoDate(r.date)<=today),meals=data.meals.filter(r=>r.date>=start&&r.date<=today),mealDays=[...new Set(meals.map(r=>r.date))];const totals=(key:'calories'|'protein'|'carbs'|'fat')=>mealDays.map(day=>meals.filter(r=>r.date===day).reduce((sum,m)=>sum+m[key],0));const balance=weeklyMuscleBalance(data.workouts,exercises,today);const checkins=data.checkins.filter(r=>r.date>=start&&r.date<=today);return {period:{from:start,to:today},workouts:{completed:weekly.length,plannedDays:data.plannedDays},nutrition:{recordedDays:mealDays.length,calories:mean(totals('calories')),protein:mean(totals('protein')),carbs:mean(totals('carbs')),fat:mean(totals('fat'))},weight:data.weights.slice(-10).map(r=>({date:r.date,value:r.value})),checkins:{count:checkins.length,sleepHours:mean(checkins.flatMap(r=>r.sleep_hours===null?[]:[r.sleep_hours])),energy:mean(checkins.flatMap(r=>r.energy===null?[]:[r.energy]))},pain:{count:data.pain.length,regions:[...new Set(data.pain.map(r=>r.region))].filter(r=>['ombro','joelho','lombar','cotovelo','punho','quadril','outra'].includes(r))},plateaus:detectPlateaus(data.workouts,today).filter(p=>exercises.some(e=>e.id===p.exerciseId||e.name===p.name)).map(p=>({exercise:exercises.find(e=>e.id===p.exerciseId||e.name===p.name)!.name,before:p.before,after:p.after,sessions:p.sessions,days:p.stalledDays})),balance:{from:balance.from,to:balance.to,weekly:balance.weekly,push:balance.push,pull:balance.pull,upper:balance.upper,lower:balance.lower,enough:balance.enough,unknownSets:balance.unknown},habits:data.habits.filter(h=>!h.archived).slice(0,30).map((h,index)=>({index,...habitStats(h,data.habitLogs,today),calendar:undefined})),wellbeingRisk:data.wellbeingRisk};}
export type DataQuery={kind:'best_lift'|'avg_nutrient'|'trend_weight'|'workouts_count'|'habit_streak'|'out_of_scope';exerciseId:string|null;nutrient:'calories'|'protein'|'carbs'|'fat'|null;habitIndex:number|null;from:string;to:string};
const nullableString={type:['string','null']};
export const QUERY_SCHEMA={type:'object',additionalProperties:false,required:['kind','exerciseId','nutrient','habitIndex','from','to'],properties:{kind:{type:'string',enum:['best_lift','avg_nutrient','trend_weight','workouts_count','habit_streak','out_of_scope']},exerciseId:{...nullableString,enum:[null,...exercises.map(e=>e.id)]},nutrient:{...nullableString,enum:[null,'calories','protein','carbs','fat']},habitIndex:{type:['integer','null'],minimum:0,maximum:29},from:{type:'string'},to:{type:'string'}}};
function validDate(date:unknown):date is string{return typeof date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date+'T00:00:00Z'))&&new Date(date+'T00:00:00Z').toISOString().slice(0,10)===date;}
export function parseQuery(raw:string,today:string):DataQuery{const q=JSON.parse(raw);if(!q||Object.keys(q).sort().join()!==['kind','exerciseId','nutrient','habitIndex','from','to'].sort().join()||!['best_lift','avg_nutrient','trend_weight','workouts_count','habit_streak','out_of_scope'].includes(q.kind)||!validDate(q.from)||!validDate(q.to)||q.to>today||q.from>q.to||Date.parse(q.from)<Date.parse(today)-89*86400000)throw new Error('query');if(q.exerciseId!==null&&!exercises.some(e=>e.id===q.exerciseId))throw new Error('exercise');if(q.nutrient!==null&&!['calories','protein','carbs','fat'].includes(q.nutrient))throw new Error('nutrient');if(q.habitIndex!==null&&(!Number.isInteger(q.habitIndex)||q.habitIndex<0||q.habitIndex>29))throw new Error('habit');if(q.kind==='best_lift'&&!q.exerciseId||q.kind==='avg_nutrient'&&!q.nutrient||q.kind==='habit_streak'&&q.habitIndex===null)throw new Error('params');return q;}
export function executeQuery(q:DataQuery,data:CoachData){const within=(date:string)=>isoDate(date)>=q.from&&isoDate(date)<=q.to;const source={from:q.from,to:q.to,records:0,unit:''};switch(q.kind){case'best_lift':{const ex=exercises.find(e=>e.id===q.exerciseId)!;const performances=data.workouts.filter(r=>within(r.date)&&!r.deload).flatMap(log=>log.exercises.flatMap((entry,i)=>entry.exerciseId===ex.id||entry.name===ex.name?[exercisePerformance(log,i)]:[]));source.records=performances.filter(p=>p.effectiveSets>0).length;source.unit='kg';return {source,value:Math.max(0,...performances.map(p=>p.bestLoad))||null,estimated1RM:Math.max(0,...performances.map(p=>p.best1RM||0))||null,exercise:ex.name};}case'avg_nutrient':{const meals=data.meals.filter(m=>within(m.date)),dates=[...new Set(meals.map(m=>m.date))];source.records=dates.length;source.unit=q.nutrient==='calories'?'kcal/dia registrado':'g/dia registrado';return {source,value:mean(dates.map(date=>meals.filter(m=>m.date===date).reduce((sum,m)=>sum+m[q.nutrient!],0))),nutrient:q.nutrient};}case'trend_weight':{const values=data.weights.filter(w=>within(w.date)).sort((a,b)=>a.date.localeCompare(b.date));source.records=values.length;source.unit='kg';return {source,first:values[0]?.value??null,last:values.at(-1)?.value??null,change:values.length>1?Math.round((values.at(-1)!.value-values[0].value)*10)/10:null};}case'workouts_count':{const rows=data.workouts.filter(w=>within(w.date));source.records=rows.length;source.unit='sessões';return {source,value:rows.length};}case'habit_streak':{const habit=data.habits.filter(h=>!h.archived)[q.habitIndex!];const rows=habit?data.habitLogs.filter(l=>l.habit_id===habit.id&&within(l.date)):[];source.records=rows.length;source.unit='dias programados';return {source,value:habit?habitStats(habit,rows,q.to).current:null};}default:return {source,value:null,outOfScope:true};}}
