import React from 'react';
import {supabase} from '../lib/supabase';
import {exercises} from '../data/exercises';
import {hasAIConsent} from '../../supabase/functions/_shared/ai-consent';
import {parseCoachResponse,parseChat,type CoachChange,type CoachResponse} from '../../supabase/functions/_shared/coach-schema';
import {AIConsentSettings} from './AIConsentSettings';
import {ModalDialog} from './ModalDialog';
import type {AIConsent} from '../../supabase/functions/_shared/ai-consent';
import type {Store,Workout} from '../lib/store';
type Source={from:string;to:string;records:number;unit?:string};
export function CoachPanel({store,onConsent,beforeAsk,onSave}:{store:Store;onConsent:(consent:AIConsent|null)=>Promise<void>;beforeAsk:()=>Promise<void>;onSave:(workout:Workout)=>void}){
 const [mode,setMode]=React.useState('Coach'),[question,setQuestion]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[result,setResult]=React.useState<{response:CoachResponse;source:Source}|null>(null),[messages,setMessages]=React.useState<{question:string;answer:string;source:Source}[]>([]),[edit,setEdit]=React.useState<{workout:Workout;change:CoachChange}|null>(null);
 const generation=React.useRef(0);React.useEffect(()=>()=>{generation.current++;},[]);React.useEffect(()=>{if(!hasAIConsent(store.preferences.ai_consent)){generation.current++;setResult(null);setMessages([]);}},[store.preferences.ai_consent]);
 async function ask(action:string,q=question){setBusy(true);setError('');const version=++generation.current;try{await beforeAsk();const response=await supabase!.functions.invoke('coach',{body:action==='chat'?{action,question:q}:{action}});if(response.error)throw new Error('Não foi possível consultar. Confira conexão, consentimento, limite por hora e publicação da função.');if(version!==generation.current)return;const source=response.data.source;if(!source||typeof source.from!=='string'||typeof source.to!=='string'||!Number.isInteger(source.records))throw new Error('Resposta inválida.');if(action==='chat'){const chat=parseChat(JSON.stringify(response.data.response));setMessages(old=>[...old,{question:q,answer:chat.answer,source}].slice(-30));setQuestion('');}else setResult({response:parseCoachResponse(JSON.stringify(response.data.response)),source});}catch(err){if(version===generation.current)setError((err as Error).message);}finally{if(version===generation.current)setBusy(false);}}
 const enabled=hasAIConsent(store.preferences.ai_consent)&&store.profile.age!==null&&store.profile.age>=18;
 function apply(change:CoachChange){const target=store.workouts[change.workoutIndex];if(!target){setError('Modelo de treino indisponível.');return;}setEdit({workout:structuredClone(target),change});}
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!edit)return;const f=new FormData(e.currentTarget),ex=exercises.find(e=>e.id===edit.change.exerciseId)!;const updated={name:ex.name,exerciseId:ex.id,sets:Number(f.get('sets')),reps:String(f.get('reps')),restSeconds:Number(f.get('rest'))};const existing=edit.workout.exercises.findIndex(e=>e.exerciseId===ex.id||e.name===ex.name);const entries=existing<0?[...edit.workout.exercises,updated]:edit.workout.exercises.map((entry,i)=>i===existing?updated:entry);onSave({...edit.workout,name:String(f.get('name')).trim(),exercises:entries});setEdit(null);}
 return <section className="feature-panel"><h2>Coach e Pergunte ao Vitra</h2><p>Sugestões informativas com seus registros. O histórico do chat fica somente nesta sessão e some ao sair desta tela.</p>{!enabled?<AIConsentSettings consent={store.preferences.ai_consent} age={store.profile.age} onChange={onConsent}/>:<><div className="feature-tabs">{['Coach','Pergunte ao Vitra'].map(t=><button key={t} aria-pressed={mode===t} onClick={()=>setMode(t)}>{t}</button>)}</div>{mode==='Coach'?<><div className="feature-tabs">{[['week','Resumo da semana'],['training','O que ajustar no meu treino?'],['food','Revisar minha alimentação']].map(([action,label])=><button key={action} disabled={busy} onClick={()=>void ask(action)}>{label}</button>)}</div>{result&&<article><h3>{result.response.title}</h3><p>Origem: {result.source.from} a {result.source.to} · {result.source.records} registros combinados.</p>{result.source.records<4&&<p>Poucos dados: interprete com cautela.</p>}{result.response.observations.map((text,i)=><p key={i}>{text}</p>)}{result.response.suggestions.map((s,i)=><div key={i}><h4>{s.action}</h4><p>{s.reason}</p>{s.change&&<button disabled={Boolean(store.activeWorkout?.workoutId===store.workouts[s.change.workoutIndex]?.id)} onClick={()=>apply(s.change!)}>Aplicar (revisar antes)</button>}</div>)}</article>}</>:<><div className="feature-tabs">{['Qual foi meu melhor supino?','Quanto de proteína comi em média este mês?','Quantos treinos fiz esta semana?'].map(q=><button key={q} disabled={busy} onClick={()=>setQuestion(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();void ask('chat');}}><label>Sua pergunta<textarea maxLength={1500} value={question} onChange={e=>setQuestion(e.target.value)} required/></label><button className="primary" disabled={busy||!question.trim()}>Perguntar</button></form><button disabled={busy} onClick={()=>setMessages([])}>Apagar conversa desta sessão</button><div aria-live="polite">{messages.map((m,i)=><article key={i}><h3>{m.question}</h3><p>{m.answer}</p><p>Origem: {m.source.from} a {m.source.to} · {m.source.records} registros · {m.source.unit||'registros'}.</p>{m.source.records<4&&<p>Poucos registros para uma conclusão.</p>}</article>)}</div></>}{busy&&<p role="status">Consultando seus dados…</p>}{error&&<p role="alert">{error}</p>}<p className="sub">Não substitui um profissional de saúde. Diante de dor persistente ou sofrimento, procure orientação individual.</p></>}
 {edit&&<ModalDialog label="Revisar sugestão de treino" onClose={()=>setEdit(null)}><h2>Confirme a alteração no modelo</h2><p>A IA propôs {exercises.find(e=>e.id===edit.change.exerciseId)?.name}. O treino atual e seu histórico são preservados.</p><form onSubmit={save}><label>Nome do modelo<input name="name" defaultValue={edit.workout.name} minLength={2} maxLength={100} required/></label><label>Séries<input name="sets" type="number" min={1} max={20} defaultValue={edit.change.sets} required/></label><label>Repetições<input name="reps" defaultValue={edit.change.reps} maxLength={30} required/></label><label>Descanso (s)<input name="rest" type="number" min={0} max={600} defaultValue={edit.change.restSeconds} required/></label><button className="primary">Confirmar alteração</button></form><button onClick={()=>setEdit(null)}>Cancelar</button></ModalDialog>}
 </section>;
}
