import React from 'react';
import { completeSet,undoSet,suggestSet,historySets,estimate1RM,effective,adjustRest } from '../lib/gym';
import { useWorkoutClock } from '../lib/useWorkoutClock';
import type { Store,SetRecord } from '../lib/store';
export function GymMode({store,onChange,onFinish}:{store:Store;onChange:(patch:Partial<Store>)=>void;onFinish:()=>void}){
 const active=store.activeWorkout!,exercises=active.exercises||[],[index,setIndex]=React.useState(()=>{const i=exercises.findIndex((ex,i)=>Array.from({length:ex.sets},(_,j)=>store.sets[`${i}-${j}`]?.done).some(v=>!v));return Math.max(0,i);}),[step,setStep]=React.useState(2.5),[audio,setAudio]=React.useState(false),[notice,setNotice]=React.useState(''),[undo,setUndo]=React.useState<{key:string;set:SetRecord|undefined;rest:string|null}|null>(null);
 const ex=exercises[index],series=ex?Array.from({length:ex.sets},(_,j)=>j).find(j=>!store.sets[`${index}-${j}`]?.done):undefined;
 const [draft,setDraft]=React.useState<SetRecord>(()=>suggestSet(store,index,series||0));
 React.useEffect(()=>{setDraft(suggestSet(store,index,series||0));},[index,series,active.workoutId]);
 const {rest}=useWorkoutClock(active),previousRest=React.useRef(rest),context=React.useRef<AudioContext|null>(null);
 React.useEffect(()=>{if(previousRest.current>0&&rest===0&&!active.pausedAt){navigator.vibrate?.(150);if(audio&&context.current){const oscillator=context.current.createOscillator(),gain=context.current.createGain();gain.gain.value=.08;oscillator.connect(gain);gain.connect(context.current.destination);oscillator.start();oscillator.stop(context.current.currentTime+.15);}}previousRest.current=rest;},[rest,audio,active.pausedAt]);
 React.useEffect(()=>()=>{void context.current?.close();},[]);
 const last=ex?historySets(store.workoutLogs,ex,active.workoutId).at(-1):null;
 const best=ex?Math.max(0,...historySets(store.workoutLogs,ex).map(s=>estimate1RM(s.load,s.reps)||0)):0;
 function finish(){if(series===undefined)return;try{const key=`${index}-${series}`;setUndo({key,set:store.sets[key],rest:active.restUntil});onChange(completeSet(store,index,series,draft));setNotice(effective({...draft,done:true})&&(estimate1RM(draft.load,draft.reps)||0)>best&&best>0?'Novo recorde estimado! Série salva.':'Série salva.');if(series===ex.sets-1&&index<exercises.length-1)setIndex(index+1);}catch(err){setNotice((err as Error).message);}}
 if(!ex)return <section className="feature-panel"><p>Adicione exercícios para iniciar a sessão.</p></section>;
 return <section className="feature-panel gym-mode" aria-label="Modo academia"><div className="section-heading"><h2>{ex.name}</h2><span>{index+1} / {exercises.length}</span></div><p>{ex.sets} séries · {ex.reps} repetições</p>{last&&<p>Última vez: {last.load} kg × {last.reps}</p>}<div className="gym-series">{series===undefined?'Exercício concluído':`Série ${series+1} de ${ex.sets}`}</div><div className="feature-filters"><label>Passo de carga (kg)<input type="number" min="0.1" max="50" step="0.1" value={step} onChange={e=>setStep(Number(e.target.value)||2.5)}/></label><label>Tipo de série<select value={draft.type||'normal'} onChange={e=>setDraft({...draft,type:e.target.value as SetRecord['type']})}>{['normal','aquecimento','drop','falha'].map(t=><option key={t}>{t}</option>)}</select></label></div><div className="gym-adjust"><label>Carga (kg)<input inputMode="decimal" type="number" min={0} max={2000} step="0.1" value={draft.load} onChange={e=>setDraft({...draft,load:Number(e.target.value)})}/></label><button aria-label="Diminuir carga" onClick={()=>setDraft({...draft,load:Math.max(0,Math.round((draft.load-step)*10)/10)})}>−</button><button aria-label="Aumentar carga" onClick={()=>setDraft({...draft,load:Math.round((draft.load+step)*10)/10})}>+</button><label>Repetições<input inputMode="numeric" type="number" min={1} max={500} value={draft.reps} onChange={e=>setDraft({...draft,reps:Number(e.target.value)})}/></label><button aria-label="Diminuir repetições" onClick={()=>setDraft({...draft,reps:Math.max(1,draft.reps-1)})}>−</button><button aria-label="Aumentar repetições" onClick={()=>setDraft({...draft,reps:draft.reps+1})}>+</button></div><button className="primary gym-complete" disabled={series===undefined||Boolean(active.pausedAt)} onClick={finish}>Concluir série</button>{notice&&<div role="status">{notice}{undo&&<button onClick={()=>{onChange(undoSet(store,undo.key,undo.set,undo.rest));setIndex(Number(undo.key.split('-')[0]));setUndo(null);setNotice('Série desfeita.');}}>Desfazer</button>}</div>}
 {rest>0&&<div className="gym-rest"><strong role="timer" aria-label="Descanso">{Math.floor(rest/60)}:{String(rest%60).padStart(2,'0')}</strong><div><button onClick={()=>onChange(adjustRest(store,-15))}>−15 s</button><button onClick={()=>onChange(adjustRest(store,15))}>+15 s</button><button onClick={()=>onChange({activeWorkout:{...active,restUntil:null}})}>Pular descanso</button></div></div>}<label className="consent-check"><input type="checkbox" checked={audio} onChange={e=>{setAudio(e.target.checked);if(e.target.checked){try{context.current ||= new AudioContext();void context.current.resume();}catch{setNotice('Som indisponível neste navegador.');setAudio(false);}}}}/>Som ao terminar o descanso</label><div className="feature-tabs"><button disabled={index===0} onClick={()=>setIndex(index-1)}>Anterior</button><button disabled={index===exercises.length-1} onClick={()=>setIndex(index+1)}>Próximo</button><button onClick={onFinish}>Finalizar treino</button></div><p className="sub">Aquecimentos não contam para volume ou recordes. O tempo é recuperado ao voltar ao app.</p></section>;
}
