import React from 'react';
import { exercises,equipmentTypes,type Equipment } from '../data/exercises';
import { matchExercise } from '../lib/exerciseCatalog';
import { suggestSubstitutes,replaceSessionExercise,recurringPain,type PainReport } from '../lib/substitutes';
import { useRecords } from '../lib/useRecords';
import { localDateKey,type Store } from '../lib/store';
import { uid } from '../lib/uid';
import { ModalDialog } from './ModalDialog';
export function SessionTools({store,userId,onChange}:{store:Store;userId:string;onChange:(patch:Partial<Store>)=>void}){
 const pain=useRecords<PainReport>('pain_reports',userId),[index,setIndex]=React.useState<number|null>(null),[report,setReport]=React.useState<number|null>(null),[reason,setReason]=React.useState('Aparelho ocupado'),[gear,setGear]=React.useState<Equipment[]>([...equipmentTypes]),[also,setAlso]=React.useState(false),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);
 const active=store.activeWorkout;const original=index===null?null:active?.exercises?.[index];const catalog=original?(exercises.find(e=>e.id===original.exerciseId)||matchExercise(original.name)):null;
 const suggestions=catalog?suggestSubstitutes(catalog,{equipmentAvailable:gear}):[];
 const alerts=recurringPain(pain.rows,localDateKey());
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await pain.save({id:uid(),date:localDateKey(),region:String(f.get('region')),intensity:Number(f.get('intensity')),exercise_id:active?.exercises?.[report!]?.exerciseId||null,note:String(f.get('note'))});setReport(null);setMessage('Relato salvo. Interrompa movimentos que causem dor.');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}
 return <section className="feature-panel"><h2>Ajustar a sessão</h2>{active?.exercises?.map((ex,i)=><div className="session-tools-row" key={i}><strong>{ex.name}</strong><button onClick={()=>{setIndex(i);setAlso(false);}}>Substituir</button><button onClick={()=>setReport(i)}>Doeu / desconforto</button></div>)}{alerts.map(a=><p key={a.region} role="status">{a.region}: {a.count} relatos em 14 dias. Considere reduzir a carga ou trocar o movimento. Se persistir, procure um profissional de saúde. O app não diagnostica.</p>)}{pain.error&&<p role="alert">{pain.error}</p>}{message&&<p role="status">{message}</p>}
 {index!==null&&<ModalDialog label="Substituir exercício" onClose={()=>setIndex(null)}><h2>Substituir {original?.name}</h2><label>Motivo<select value={reason} onChange={e=>setReason(e.target.value)}><option>Aparelho ocupado</option><option>Sem o equipamento</option><option>Desconforto</option></select></label><fieldset><legend>Equipamentos disponíveis</legend>{equipmentTypes.map(e=><label key={e} className="consent-check"><input type="checkbox" checked={gear.includes(e)} onChange={()=>setGear(gear.includes(e)?gear.filter(g=>g!==e):[...gear,e])}/>{e}</label>)}</fieldset><label className="consent-check"><input type="checkbox" checked={also} onChange={e=>setAlso(e.target.checked)}/>Trocar também no modelo</label>{!catalog&&<p>Associe este exercício à biblioteca no editor para receber sugestões.</p>}{catalog&&!suggestions.length&&<p>Nenhuma opção com os equipamentos selecionados.</p>}{suggestions.map(s=><div key={s.exercise.id}><p>{s.exercise.name} · {s.exercise.equipment}{s.relaxed?' · Mesmo grupo, movimento diferente':' · Mesmo grupo e movimento'}</p><button onClick={()=>{try{onChange(replaceSessionExercise(store,index,s.exercise,reason,also));setIndex(null);}catch(err){setMessage((err as Error).message);setIndex(null);}}}>Usar {s.exercise.name}</button></div>)}<button onClick={()=>setIndex(null)}>Cancelar</button></ModalDialog>}
 {report!==null&&<ModalDialog label="Registrar desconforto" onClose={()=>setReport(null)}><h2>Como foi o desconforto?</h2><p>Se houver dor, interrompa o exercício e procure orientação.</p><form onSubmit={save}><label>Região<select name="region">{['ombro','joelho','lombar','cotovelo','punho','quadril','outra'].map(r=><option key={r}>{r}</option>)}</select></label><label>Intensidade (1 leve — 5 intensa)<input name="intensity" type="number" min={1} max={5} defaultValue={1} required/></label><label>Nota<textarea name="note" maxLength={1000}/></label><button className="primary" disabled={busy}>Salvar relato</button></form><button onClick={()=>setReport(null)}>Cancelar</button></ModalDialog>}
 </section>;
}
