import { ArrowRight, Scale, CalendarDays } from 'lucide-react';
import { weightReminder, type Store } from '../lib/store';
export function WeightCheckIn({ store, onRegister }: { store: Store; onRegister: () => void }) {
  const reminder = weightReminder(store.weights);
  return <div className={`weight-checkin ${reminder.due ? 'due' : ''}`}><span className="tile green"><Scale size={22}/></span><div><strong>{reminder.due ? 'Hora de registrar seu peso' : `Próximo registro: ${reminder.next}`}</strong><p>{reminder.due ? 'Seu acompanhamento a cada 3 dias. Inclua o contexto do treino de hoje.' : `Faltam ${reminder.daysRemaining} ${reminder.daysRemaining === 1 ? 'dia' : 'dias'}. Você também pode registrar quando quiser.`}</p></div><button className="text" onClick={onRegister}>Registrar <ArrowRight size={16}/></button></div>;
}
export function WeightProgress({ store, onRegister }: { store: Store; onRegister: () => void }) {
  const last = store.weights.at(-1), first = store.weights[0];
  const points = store.weights.slice(-20);
  const min = Math.min(...points.map(w => w.value)) - 1, max = Math.max(...points.map(w => w.value)) + 1;
  const path = points.map((w, i) => `${30 + i / Math.max(1, points.length - 1) * 540},${125 - (w.value - min) / (max - min) * 95}`).join(' ');
  return <section className="panel weight-progress"><div className="section-heading"><h2><Scale size={19}/>Seu histórico de peso</h2><button className="primary" onClick={onRegister}>Registrar peso <ArrowRight size={15}/></button></div><WeightCheckIn store={store} onRegister={onRegister}/>{last ? <><div className="weight-overview"><div><span>Último registro</span><strong>{last.value.toLocaleString('pt-BR')} <small>kg</small></strong></div><div><span>Desde o primeiro registro</span><strong>{last.value - first.value > 0 ? '+' : ''}{(last.value - first.value).toLocaleString('pt-BR', { maximumFractionDigits: 1 })} <small>kg</small></strong></div><div><span>Registros</span><strong>{store.weights.length}</strong></div></div>{points.length > 1 && <div className="weight-chart"><svg viewBox="0 0 600 160" role="img" aria-label={`Evolução dos últimos ${points.length} pesos: de ${points[0].value} a ${last.value} kg`}><defs><linearGradient id="weight-fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#73bca1" stopOpacity=".2"/><stop offset="1" stopColor="#73bca1" stopOpacity="0"/></linearGradient></defs>{[35, 80, 125].map(y => <line key={y} x1="25" x2="575" y1={y} y2={y} stroke="var(--border)" strokeDasharray="4 4"/>)}<polygon points={`30,145 ${path} 570,145`} fill="url(#weight-fill)"/><polyline points={path} fill="none" stroke="#65af92" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>{points.map((w, i) => <circle key={i} cx={30 + i / Math.max(1, points.length - 1) * 540} cy={125 - (w.value - min) / (max - min) * 95} r="3.5" fill="#65af92" stroke="var(--surface)" strokeWidth="2"/>)}</svg><div><span>{points[0].date}</span><span>{last.date}</span></div></div>}{store.weights.slice().reverse().map((w, i) => <div className="meal-row weight-row" key={`${w.date}-${i}`}><span className="tile green"><CalendarDays size={18}/></span><div><strong>{w.date}</strong><small>{w.workout || 'Contexto não registrado'}{w.workoutMinutes ? ` · ${w.workoutMinutes} min` : ''}{w.cardioKm ? ` · Cardio ${w.cardioKm.toLocaleString('pt-BR')} km` : ''}</small>{w.note && <small>{w.note}</small>}</div><b>{w.value.toLocaleString('pt-BR')} kg</b></div>)}</> : <div className="empty"><p>Seu ponto de partida é só seu. Registre o peso para começar.</p></div>}</section>;
}
